### ISSUE TITLE
mettere le icone in mezzo la pagina e a tutto

### ISSUE THREAD

**Issue by giacomogagliano** [Zion-PTC/zion-network-state#10]
```
  // TODO mettere le icone in mezzo la pagina e a tutto
```

https://github.com/Zion-PTC/zion-network-state/blob/690c67bdb77ef61fe685e07d8d291e3cba9e5f68/packages/ui/src/pages/classes/icon/index.tsx#L5

**Comment by ariannatnl** [comment]
fatto e creato pull request issue 10
