### ISSUE TITLE
per non far buggare il render ho aggiunto un

### ISSUE THREAD

**Issue by giacomogagliano** [Zion-PTC/zion-network-state#3]
```
      // TODO per non far buggare il render ho aggiunto un
```

https://github.com/Zion-PTC/zion-network-state/blob/ceca1c6c3e33764172021f14df298183ed88c09a/apps/nft-minter/src/components/MDContent.tsx#L31

**Comment by ariannatnl** [comment]
questo lo chiudiamo o devi aggiungere qualcosa'altr?

**Comment by giacomogagliano** [comment]
lo chiudo io
