### ISSUE TITLE
@ariannatnl cancellare le v1 da tutti i file contenenti i

### ISSUE THREAD

**Issue by giacomogagliano** [Zion-PTC/zion-network-state#31]
https://github.com/Zion-PTC/zion-network-state/blob/4927182e1469eef37d28dd3d4fb2f398d265deef/packages/ui/src/HTML/React/classes/Icon/ArrowBack/ArrowBack_v1.tsx#L11

**Comment by ariannatnl** [comment]
fatto manca solo loading
