### ISSUE TITLE
non capisco se devo aggiungere la nuova basenoiz anq

### ISSUE THREAD

**Issue by ariannatnl** [Zion-PTC/zion-network-state#35]
```
//TODO non capisco se devo aggiungere la nuova basenoiz
```

https://github.com/Zion-PTC/zion-network-state/blob/88fc40a48af968850c6af836bee4d8df2349b701/packages/ui/src/HTML/React/classes/IconPath/IconPath_v1.tsx#L69

**Comment by giacomogagliano** [comment]
niente ansia tutto ok ahahahaha
