### ISSUE TITLE
toglierlo dal cazzo?? ti ricordi cos'era?

### ISSUE THREAD

**Issue by giacomogagliano** [Zion-PTC/zion-network-state#5]
```
  // TODO toglierlo dal cazzo?? ti ricordi cos'era?
```

https://github.com/Zion-PTC/zion-network-state/blob/32904ea3f923dd1a721f0d2eb57f2cc9a0a37a8e/apps/nft-minter/src/components/GlobalStyle.tsx#L19

**Comment by ariannatnl** [comment]
è IL LOADER QUELLO ROTONDO CHE GIRAVA MI SEMBRA

**Comment by giacomogagliano** [comment]
allora si puo togliere ... ho creato una cartella Loaders in style dentro UI ... l'ho già messo li
